import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./nav/NavBar";
import ToastProvider from "./providers/ToastProvider";

export const metadata: Metadata = {
  title: "Lemobil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className="bg-gradient-to-br from-gray-50 via-white to-blue-50"
      >
        <ToastProvider />
        <NavBar />
        <main className="w-full px-3 sm:px-5 md:px-6 lg:px-8 pt-8 sm:pt-10 md:pt-12 lg:pt-16 pb-8 sm:pb-10 md:pb-12 min-h-screen">
          <div className="container mx-auto max-w-7xl">{children}</div>
        </main>
      </body>
    </html>
  );
}
