import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./nav/NavBar";
import ToastProvider from "./providers/ToastProvider";

export const metadata: Metadata = {
  title: "Lemobil",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ToastProvider />
        <NavBar />
        <main className="container mx-auto px-5 pt-10">{children}</main>
      </body>
    </html>
  );
}
