FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build  
WORKDIR /app

COPY Mobil_Lelang_Backend.sln ./
COPY BiddingService/BiddingService.csproj ./src/BiddingService/
COPY Contracts/Contracts.csproj ./src/Contracts/

RUN dotnet restore ./src/BiddingService/BiddingService.csproj

COPY . .
RUN dotnet publish ./BiddingService/BiddingService.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
EXPOSE 80
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BiddingService.dll"]
